Fix link href is URI Sheme
jhildenbiddle/get-css-data pull request #15
Opened 2022-04-15 01:33 UTC by wggit2020

Hello, when we use `css-vars-ponyfill` to get the css  in IE, `<link href="data:text/css,...">` will get an error: `SCRIPT5: Access is denied.` 

I found the reason, and made changes in the code.

I also made a demo to show the problem: [css-var-ponyfill-fix-link-href-data-demo.zip](https://github.com/jhildenbiddle/get-css-data/files/8493242/css-var-ponyfill-fix-link-href-data-demo.zip).

Thank you for project.

2022-04-17 19:55 UTC, jhildenbiddle commented
This looks good, @wggit2020. Once appropriate tests are added I can merge the PR.

Also, I am genuinely curious: why use `<link href="data:text/css,...">` instead of a simple `<style>` element for injecting into the DOM?

2022-04-17 19:55 UTC, jhildenbiddle requested changes
This looks good, @wggit2020. Once appropriate tests are added I can merge the PR.

Also, I am genuinely curious: why use <link href="data:text/css,..."> instead of a simple <style> element for injecting into the DOM?

2022-04-18 02:18 UTC, wggit2020 commented
1 Should I add the tests or should I just wait?
2 Actually this problem is used in the `TOAST UI ImageEditor`.

2022-04-18 22:52 UTC, jhildenbiddle commented
@wggit2020 --

Yes, please add the tests to your PR.

Thanks!

2022-04-20 10:08 UTC, wggit2020 commented
@jhildenbiddle I have added the tests.

2022-04-20 15:08 UTC, jhildenbiddle requested changes
Thank you for adding these tests, @wggit2020. Very much appreciated. 

I've made a few change requests inline. Simple stuff, then we should be all set to merge and release.

2022-04-20 15:08 UTC, jhildenbiddle commented on tests/get-css.test.js
> +            const expected = fixtures['style-uri-scheme-out.css'];
1. Instead of adding a new fixture, let's reuse one of the existing ones
2. Let's add the characterset to the URI



```js
const encodedCSS = encodeURIComponent(fixtures['style1.css']);
const URIScheme  = `data:text/css;charset=UTF-8,${encodedCSS}`;
const expected   = fixtures['style1.css'];
```

2022-04-20 15:08 UTC, jhildenbiddle commented on tests/get-css.test.js
> +            const expected = fixtures['style-uri-scheme-out.css'].repeat(linkElms.length);
Same as above (reuse existing fixture and add characterset to URI):

```js
const encodedCSS = encodeURIComponent(fixtures['style1.css']);
const URIScheme  = `data:text/css;charset=UTF-8,${encodedCSS}`;
const linkElms   = createTestElms(`<link rel="stylesheet" href="${URIScheme}">`.repeat(2));
const expected   = fixtures['style1.css'].repeat(linkElms.length);
```

2022-04-20 15:08 UTC, jhildenbiddle commented on src/get-css.js
> +                    if (settings.useCSSOM) {
We should add tests for when `useCSSOM` it `true` since this PR contains new code to handle this scenario. To keep things simple, just duplicate the existing `options.useCSSOM` test and have it test a `<link href="data:...">` element instead of a `<style>` element. 

See here:

https://github.com/jhildenbiddle/get-css-data/blob/68f964d0a45b2e46d839730c1c45ad67b9609fc3/tests/get-css.test.js#L409

You'll need to rename the tests to something like:

- Existing test: "options.useCSSOM with <style>"
- New test: "options.useCSSOM with <link> with data URI"

2022-04-20 15:08 UTC, jhildenbiddle commented on tests/fixtures/style-uri-scheme-out.css
> +p{color:green;}
We can remove this new external fixture once the other changes are made.

2022-04-21 03:07 UTC, wggit2020 commented on tests/get-css.test.js
> +            const expected = fixtures['style-uri-scheme-out.css'];
Such changes are very helpful and better.

2022-04-21 03:11 UTC, wggit2020 commented on src/get-css.js
> +                    if (settings.useCSSOM) {
I did not notice this and have added. I learn something new.

2022-04-21 03:14 UTC, wggit2020 commented
@jhildenbiddle I have changed all change requests you made. All very helpful. Thank you.

2022-04-21 17:50 UTC, jhildenbiddle approved these changes
This looks great, @wggit2020! Thank you for your contribution and patience while working through all of the requested changes. Very much appreciated!

2022-04-21 17:52 UTC, merged

2022-04-21 19:30 UTC, jhildenbiddle commented
@wggit2020 -- Published in 2.1.0.

2022-04-22 01:24 UTC, wggit2020 commented
@jhildenbiddle  OK, it's nice. It's a good precess. In addition, maybe need to update the dependencies of `css-vars-ponyfill`.

2022-04-22 01:27 UTC, jhildenbiddle commented
Yep. That's the plan. :)